name: ci

# Define when the workflow should run: on pull requests to the "master" branche, and on pushes to this branche.
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  # Job for running tests
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    # Step 1: Check out the code repository    
    - uses: actions/checkout@v4
      with:
        lfs: true

    - uses: ./.github/actions/build

    - run: npm run lint
      shell: bash
      working-directory: templates

    - run: npm test
      shell: bash
      working-directory: templates

    - run: choco install wkhtmltopdf
      if: matrix.os == 'windows-latest'

    - run: dotnet test -c Release -f net8.0 --no-build --collect:"XPlat Code Coverage"

    - run: dotnet test -c Release -f net7.0 --no-build --collect:"XPlat Code Coverage"
      if: matrix.os == 'ubuntu-latest'

    - run: dotnet test -c Release -f net6.0 --no-build --collect:"XPlat Code Coverage"
      if: matrix.os == 'ubuntu-latest'

    - uses: codecov/codecov-action@v3
      if: matrix.os == 'ubuntu-latest'

    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- docs/docfx.json

    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- metadata samples/seed/docfx.json
    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- metadata samples/seed/docfx.json --outputFormat markdown --output samples/seed/md
    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- metadata samples/seed/docfx.json --outputFormat markdown --output samples/seed/md2 --namespaceLayout nested --memberLayout separatePages
    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- build samples/seed/docfx.json --output docs/_site/seed

    - uses: actions/upload-artifact@v3
      if: matrix.os == 'ubuntu-latest'
      with:
        name: site
        path: docs/_site

  publish-docs:
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: site
        path: site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site

  